### ISSUE TITLE
undefined method `convert_to_id' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dblock** [dblock/slack-sup2#3]
```
[slack-sup2] [2023-07-10 18:27:58] E, [2023-07-10T18:27:58.779841 #1] ERROR -- : undefined method `convert_to_id' for nil:NilClass (NoMethodError)
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mailchimp_api_v3-0.2.18/lib/mailchimp_api_v3/member.rb:11:in `add_id_to'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/mailchimp_api_v3-0.2.18/lib/mailchimp_api_v3/member.rb:70:in `create_or_update'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/slack-ruby-bot-server-mailchimp-0.2.0/lib/slack-ruby-bot-server/mailchimp/lifecycle.rb:40:in `block in <top (required)>'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/slack-ruby-bot-server-2.1.0/lib/slack-ruby-bot-server/service.rb:143:in `block in run_callbacks'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/slack-ruby-bot-server-2.1.0/lib/slack-ruby-bot-server/service.rb:142:in `each'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/slack-ruby-bot-server-2.1.0/lib/slack-ruby-bot-server/service.rb:142:in `run_callbacks'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/slack-ruby-bot-server-2.1.0/lib/slack-ruby-bot-server/service.rb:42:in `create!'
[slack-sup2] [2023-07-10 18:27:58] /workspace/lib/api/endpoints/teams_endpoint.rb:111:in `block (2 levels) in <class:TeamsEndpoint>'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:58:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:58:in `block (2 levels) in generate_api_method'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:205:in `instrument'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:57:in `block in generate_api_method'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:328:in `execute'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:261:in `block in run'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:205:in `instrument'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:241:in `run'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:316:in `block in build_stack'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/middleware/base.rb:36:in `call!'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/middleware/base.rb:29:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/middleware/error.rb:39:in `block in call!'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/middleware/error.rb:38:in `catch'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/middleware/error.rb:38:in `call!'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/middleware/base.rb:29:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/rack-2.2.6.3/lib/rack/head.rb:12:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:225:in `call!'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/endpoint.rb:219:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router/route.rb:58:in `exec'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:120:in `process_route'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:74:in `block in identity'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:94:in `transaction'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:72:in `identity'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:56:in `block in call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:136:in `with_optimization'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/router.rb:55:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/api/instance.rb:165:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/grape.rb:125:in `call_with_new_relic'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/api/instance.rb:70:in `call!'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/api/instance.rb:65:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/grape-1.7.0/lib/grape/api.rb:81:in `call'
[slack-sup2] [2023-07-10 18:27:58] /workspace/lib/api/middleware.rb:33:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/rack-server-pages-0.1.0/lib/rack/server_pages.rb:46:in `serving'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/rack-server-pages-0.1.0/lib/rack/server_pages.rb:36:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/rack-robotz-0.0.4/lib/rack/robotz/middleware.rb:20:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/rack-cors-2.0.0/lib/rack/cors.rb:102:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/configuration.rb:269:in `call'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/request.rb:98:in `block in handle_request'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/request.rb:97:in `handle_request'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/server.rb:431:in `process_client'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/server.rb:233:in `block in run'
[slack-sup2] [2023-07-10 18:27:58] /layers/heroku_ruby/gems/vendor/bundle/ruby/2.7.0/gems/puma-6.1.0/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
[s
```

**Comment by dblock** [comment]
Updated mailchimp library in https://github.com/dblock/slack-sup2/commit/f949325b66c4a98b5e05bdbdf4cc5e2a15eebdf4, seems fixed.
